version: "3"

services:
  postgres:
    container_name: "postgres"
    build: ./docker/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: serverdev,servertest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  server:
    container_name: "server"
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:10020:10020"
      - "9229:9229"
    expose:
      - 9229
    volumes:
      - ./services/server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - migrate
    env_file:
      - ./services/server/.env
    command: ["yarn", "start"]

  migrate:
    container_name: "migrate"
    build:
      context: ./services/server
      dockerfile: Dockerfile
    volumes:
      - ./services/server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    env_file:
      - ./services/server/.env
    command: ["yarn", "migrate:all"]